import 'package:ekatapoolcompanion/models/coindata.dart';

List<CoinData> coinDatas = [
  CoinData(
      coinName: "Baza",
      coinLogoPath: "assets/images/baza.png",
      poolAddress: "70.35.206.105",
      poolPortCPU: 3333,
      poolPortGPU: 5555,
      coinAlgo: "cn-pico",
      cpuMineable: true),
  CoinData(
      coinName: "Atanapicoin",
      coinLogoPath: "assets/images/atanapi.png",
      poolAddress: "gb.mining4people.com",
      poolPortCPU: 3425,
      poolPortGPU: 3425,
      coinAlgo: "ghostrider",
      cpuMineable: true),
  CoinData(
      coinName: "BabaCoin",
      coinLogoPath: "assets/images/babacoin.png",
      poolAddress: "gb.mining4people.com",
      poolPortCPU: 3419,
      poolPortGPU: 3419,
      coinAlgo: "ghostrider",
      cpuMineable: true),
  CoinData(
      coinName: "ButKoin",
      coinLogoPath: "assets/images/butkoin.png",
      poolAddress: "gb.mining4people.com",
      poolPortCPU: 3350,
      poolPortGPU: 3350,
      coinAlgo: "ghostrider",
      cpuMineable: true),
  CoinData(
      coinName: "Jagoan",
      coinLogoPath: "assets/images/jagoan.png",
      poolAddress: "gb.mining4people.com",
      poolPortCPU: 3414,
      poolPortGPU: 3414,
      coinAlgo: "ghostrider",
      cpuMineable: true),
  CoinData(
      coinName: "Raptoreum",
      coinLogoPath: "assets/images/raptoreum.png",
      poolAddress: "gb.mining4people.com",
      poolPortCPU: 3101,
      poolPortGPU: 3101,
      coinAlgo: "ghostrider",
      cpuMineable: true),
  CoinData(
      coinName: "Yerbas",
      coinLogoPath: "assets/images/yerbas.png",
      poolAddress: "gb.mining4people.com",
      poolPortCPU: 3380,
      poolPortGPU: 3380,
      coinAlgo: "ghostrider",
      cpuMineable: true),
  CoinData(
      coinName: "Arielcoin",
      coinLogoPath: "assets/images/arielcoin.png",
      poolAddress: "us.mining4people.com",
      poolPortCPU: 3345,
      poolPortGPU: 3345,
      coinAlgo: "kawpow",
      cpuMineable: false),
  CoinData(
      coinName: "Meowcoin",
      coinLogoPath: "assets/images/meowcoin.png",
      poolAddress: "us.mining4people.com",
      poolPortCPU: 3409,
      poolPortGPU: 3409,
      coinAlgo: "kawpow",
      cpuMineable: false),
  CoinData(
      coinName: "Neoxa",
      coinLogoPath: "assets/images/neoxa.png",
      poolAddress: "us.mining4people.com",
      poolPortCPU: 3399,
      poolPortGPU: 3399,
      coinAlgo: "kawpow",
      cpuMineable: false),
  CoinData(
      coinName: "Ravencoin",
      coinLogoPath: "assets/images/ravencoin.png",
      poolAddress: "us.mining4people.com",
      poolPortCPU: 3346,
      poolPortGPU: 3346,
      coinAlgo: "kawpow",
      cpuMineable: false),
  CoinData(
      coinName: "VirtualEmpire",
      coinLogoPath: "assets/images/virtualempire.png",
      poolAddress: "us.mining4people.com",
      poolPortCPU: 3427,
      poolPortGPU: 3427,
      coinAlgo: "kawpow",
      cpuMineable: false),
  CoinData(
      coinName: "KawKaw",
      coinLogoPath: "assets/images/kawkaw.png",
      poolAddress: "us.mining4people.com",
      poolPortCPU: 3404,
      poolPortGPU: 3404,
      coinAlgo: "kawpow",
      cpuMineable: false)
];
